# Generated by Django 5.2 on 2025-05-27 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0004_alter_athleteinfo_goals_alter_athleteinfo_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athleteinfo',
            old_name='athlete',
            new_name='user_id',
        ),
    ]
