# Generated by Django 5.2 on 2025-05-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0013_alter_collectibleitem_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectibleitem',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
