# Generated by Django 5.2 on 2025-05-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0014_alter_collectibleitem_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectibleitem',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
