# Generated by Django 5.2 on 2025-05-31 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0017_alter_collectibleitem_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectibleitem',
            name='items',
            field=models.ManyToManyField(related_name='collectible_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
